### ISSUE TITLE
libssl.so.3: cannot open shared object file

### ISSUE THREAD

**Issue by rknightion** [mgs255/handel#1]
On a new install of Ubuntu 20.04 when running handel I get:
`handel: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory`

I have installed build-essential and libssl-dev but so far no dice

**Comment by mgs255** [comment]
Thanks for the bug report @rknightion.   I've released version 0.3.14 which switches to using rustls instead of OpenSSL which seems to work ok in my test build.

I've also added Dockerfile which I used to test building on Ubuntu 22.04.
